name: CI_CD_Pipeline

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install flake8
      - name: Run Linting
        run: flake8 . --exit-zero
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run Tests
        run: pytest test_model.py
  deployment:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Deploy Model
        run: echo "Deploying the model..."
